trigger:
  branches:
    include:
      - main

pool:
  name: SelfHosted        # or the custom agent pool nameee
  demands:
    - Agent.Name -equals Agennt

steps:
  - script: echo "Building app..."
    displayName: 'CI: Build'

  - script: echo "Simulating docker push"
    displayName: 'CI: Push Image'

