trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "Building app..."
    displayName: 'CI: Build'

  - script: echo "Simulating docker push"
    displayName: 'CI: Push Image'
