trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ciPipelineAlias  # This is just an alias
      source: azure-pipelines-ci  # 👈 Must match your CI pipeline name exactly
      trigger:
        branches:
          include:
            - main

pool:
  name: SelfHosted        # Replace with your actual pool name if different
  demands:
    - Agent.Name
    - equals
    - Agennt

stages:
- stage: Deploy
  displayName: CD: Deploy Stage
  condition: succeeded()
  jobs:
    - job: DeployJob
      steps:
        - script: echo "CD: Deploying application..."
          displayName: 'CD Step'
