trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ciPipelineAlias  # This is just an alias you choose
      source: azure-pipelines-ci  # 👈 Must match the actual CI pipeline name
      trigger:
        branches:
          include:
            - main  # or any branch where CI is running — you can keep this as main

pool:
  name: SelfHosted        # or the custom agent pool name
  demands:
    - Agent.Name -equals Agennt

stages:
- stage: Deploy
  displayName: CD: Deploy Stage
  condition: succeeded()
  jobs:
    - job: DeployJob
      steps:
        - script: echo "CD: Deploying application..."
          displayName: 'CD Step'
